### ISSUE TITLE
Format of Twitter Data

### ISSUE THREAD

**Issue by Kittyuzu1207** [pablobarbera/twitter_ideology#13]
Hi, Pablo! Thanks for your amazing work. I wonder if I have crawled the following list information already, what format should I organize the data so that I can estimate ideology with MCMC method directly? Since I'm a beginner of R, I don't know how to use our data to replace the step of using Twitter API.
Thank you so much!

**Comment by pablobarbera** [comment]
Hi @Kittyuzu1207! Thanks for your kind words. If you already have the followers lists, you can skip to the step of creating the adjacency matrix. The code here probably is the cleanest way of doing it: https://github.com/pablobarbera/twitter_ideology/blob/master/2016-election/02-create-adjacency-matrix.R 

Feel free to ping me over email, since I don't check the issues here very frequently.

**Comment by Kittyuzu1207** [comment]
> Hi @Kittyuzu1207! Thanks for your kind words. If you already have the followers lists, you can skip to the step of creating the adjacency matrix. The code here probably is the cleanest way of doing it: https://github.com/pablobarbera/twitter_ideology/blob/master/2016-election/02-create-adjacency-matrix.R
> 
> Feel free to ping me over email, since I don't check the issues here very frequently.

Got it~ Thank you so much for your reply!😊
